import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"], // Optionally add subsets if needed
});

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Check if locale is available in localStorage
  const sysLocale =
    typeof window !== "undefined" && localStorage.getItem("locale")
      ? localStorage.getItem("locale") || "en"
      : locale;

  return (
    <html lang={sysLocale} dir={sysLocale === "ar" ? "rtl" : "ltr"}>
      <body className={font.className}>{children}</body>
    </html>
  );
}
